export const OBSERVABILITY_OPTIONS = Symbol("OBSERVABILITY_OPTIONS");
export const OBSERVABILITY_ACTOR_RESOLVER = Symbol(
  "OBSERVABILITY_ACTOR_RESOLVER",
);
export const OBSERVABILITY_REQUEST_CONTEXT_RESOLVER = Symbol(
  "OBSERVABILITY_REQUEST_CONTEXT_RESOLVER",
);
export const OBSERVABILITY_PAYLOAD_SANITIZER = Symbol(
  "OBSERVABILITY_PAYLOAD_SANITIZER",
);
export const OBSERVABILITY_REQUEST_LOG_ERROR_MAPPER = Symbol(
  "OBSERVABILITY_REQUEST_LOG_ERROR_MAPPER",
);
export const OBSERVABILITY_AUDIT_MAPPER = Symbol(
  "OBSERVABILITY_AUDIT_MAPPER",
);
export const OBSERVABILITY_REQUEST_LOGS_REPOSITORY = Symbol(
  "OBSERVABILITY_REQUEST_LOGS_REPOSITORY",
);
export const OBSERVABILITY_AUDIT_EVENTS_REPOSITORY = Symbol(
  "OBSERVABILITY_AUDIT_EVENTS_REPOSITORY",
);

export const OBSERVABILITY_CONTEXT_HEADER = "x-observability-context";
export const OBSERVABILITY_AUDIT_CONTEXT_HEADER = "auditContext";
